# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class UpdateEnterpriseConnectionResponse
        
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # An enterprise connection
        field :schemas_enterprise_connection, Crystalline::Nilable.new(Models::Components::SchemasEnterpriseConnection)

        
        def initialize(content_type:, status_code:, raw_response:, schemas_enterprise_connection: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @schemas_enterprise_connection = schemas_enterprise_connection
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @schemas_enterprise_connection == other.schemas_enterprise_connection
          true
        end
      end
    end
  end
end
