# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # Present when the enterprise connection uses OIDC
      class OauthConfig
        
        include Crystalline::MetadataFields

        # OAuth config ID
        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id') } }
        # Custom OIDC provider display name
        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('name') } }
        # OAuth provider key (e.g. oidc_custom, oidc_ghe_*, oidc_gitlab_ent_*)
        field :provider_key, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('provider_key') } }
        # Unix timestamp in milliseconds when the config was created
        field :created_at, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('created_at') } }
        # Unix timestamp in milliseconds when the config was last updated
        field :updated_at, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('updated_at') } }
        # OAuth client ID
        field :client_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('client_id') } }
        # OIDC discovery URL
        field :discovery_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('discovery_url') } }
        # Logo URL for the provider
        field :logo_public_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('logo_public_url') } }

        
        def initialize(id: nil, name: nil, provider_key: nil, created_at: nil, updated_at: nil, client_id: nil, discovery_url: nil, logo_public_url: nil)
          @id = id
          @name = name
          @provider_key = provider_key
          @created_at = created_at
          @updated_at = updated_at
          @client_id = client_id
          @discovery_url = discovery_url
          @logo_public_url = logo_public_url
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @provider_key == other.provider_key
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          return false unless @client_id == other.client_id
          return false unless @discovery_url == other.discovery_url
          return false unless @logo_public_url == other.logo_public_url
          true
        end
      end
    end
  end
end
