# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class SchemasEnterpriseConnection
        
        include Crystalline::MetadataFields

        # The enterprise connection ID
        field :id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id'), required: true } }
        # The display name of the connection
        field :name, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('name'), required: true } }
        # Whether the enterprise connection is active
        field :active, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('active'), required: true } }
        # Domains associated with the enterprise connection
        field :domains, Crystalline::Array.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('domains'), required: true } }
        # Unix timestamp in milliseconds when the connection was created
        field :created_at, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('created_at'), required: true } }
        # Unix timestamp in milliseconds when the connection was last updated
        field :updated_at, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('updated_at'), required: true } }
        # Controls whether to update the user's attributes on each sign-in
        field :sync_user_attributes, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('sync_user_attributes') } }
        # When true, users cannot add additional identifications when using this connection
        field :disable_additional_identifications, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('disable_additional_identifications') } }
        # Organization ID when the connection is linked to an organization
        field :organization_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('organization_id') } }
        # Present when the enterprise connection uses SAML
        field :saml_connection, Crystalline::Nilable.new(Models::Components::SchemasEnterpriseConnectionSamlConnection), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('saml_connection') } }
        # Present when the enterprise connection uses OIDC
        field :oauth_config, Crystalline::Nilable.new(Models::Components::OauthConfig), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('oauth_config') } }

        
        def initialize(id:, name:, active:, domains:, created_at:, updated_at:, sync_user_attributes: nil, disable_additional_identifications: nil, organization_id: nil, saml_connection: nil, oauth_config: nil)
          @id = id
          @name = name
          @active = active
          @domains = domains
          @created_at = created_at
          @updated_at = updated_at
          @sync_user_attributes = sync_user_attributes
          @disable_additional_identifications = disable_additional_identifications
          @organization_id = organization_id
          @saml_connection = saml_connection
          @oauth_config = oauth_config
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @active == other.active
          return false unless @domains == other.domains
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          return false unless @sync_user_attributes == other.sync_user_attributes
          return false unless @disable_additional_identifications == other.disable_additional_identifications
          return false unless @organization_id == other.organization_id
          return false unless @saml_connection == other.saml_connection
          return false unless @oauth_config == other.oauth_config
          true
        end
      end
    end
  end
end
